services:
  pwsh-cron:
    image: nickadam/pwsh-cron:latest
    build: .
    environment:
      - CRONJOB=* * * * * pwsh -File /root/script.ps1
      - SCRIPT=Get-Date | Out-File -Append /var/log/cron.log
